# edit this file and save as process_config.yaml when running locally
# contains how many gas mixtures are added when interpolating, the range that is used for
# calculating pmf, and the standard deviation of normal distributions around experimental masses
# densities of mofs, experimental masses for each mof, the mofs included in the analysis, the gases
# considered, and the mofs in the end array

num_mixtures: 10
mrange: .05
stdev: 0.1

number_mofs:
  - 10
  - 10

number_bins: 31

mof_array:
  - IRMOF-1
  - HKUST-1
  - NU-125
  - UIO-66
  - ZIF-8
  - MgMOF-74
  - MOF-177
  - NU-100
  - MOF-801
  - ALUKIC
  - AMIMAL
  - AXUHEH
  - BAZGAM
  - BIWSEG
  - EDUVOO
  - FIDRIV
  - GAGZEV
  - GUPBEZ
  - HABQUY
  - HIFTOG
  - JEWCAP
  - KICXAX
  - KIFJUF
  - KINKAV
  - LODPUQ
  - LOFVUY
  - MUDTEL
  - NAYZOE
  - NIBHOW
  - NIBJAK
  - OFEREX
  - RAVXET
  - RAVXIX
  - RAVXOD
  - RUTNOK
  - SADLEQ
  - SAPBIW
  - SICZOV
  - TOHSAL
  - UKUPUL
  - VETTIZ
  - WIYMOG
  - WUNSEE01
  - XAFFAN
  - XAFXOT
  - XAHQAA
  - XALTIP
  - XUKYEI
  - XUWVUG
  - YEQRIV

mofs:
  IRMOF-1:
    density: 0.5934
  HKUST-1:
    density: 0.8791
  NU-125:
    density: 0.5783
  UIO-66:
    density: 1.219
  ZIF-8:
    density: 0.9246
  MgMOF-74:
    density: 0.88325
  MOF-177:
    density: 0.4268
  NU-100:
    density: 0.29103
  MOF-801:
    density: 1.8917
  ALUKIC:
    density: 0.567
  AMIMAL:
    density: 0.989
  AXUHEH:
    density: 1.065
  BAZGAM:
    density: 0.127
  BIWSEG:
    density: 0.467
  EDUVOO:
    density: 0.373
  FIDRIV:
    density: 0.698
  GAGZEV:
    density: 0.279
  GUPBEZ:
    density: 2.454
  HABQUY:
    density: 0.289
  HIFTOG:
    density: 1.166
  JEWCAP:
    density: 1.115
  KICXAX:
    density: 3.585
  KIFJUF:
    density: 0.822
  KINKAV:
    density: 1.210
  LODPUQ:
    density: 1.074
  LOFVUY:
    density: 1.078
  MUDTEL:
    density: 0.559
  NAYZOE:
    density: 0.499
  NIBHOW:
    density: 0.280
  NIBJAK:
    density: 0.223
  OFEREX:
    density: 1.568
  RAVXET:
    density: 0.327
  RAVXIX:
    density: 0.235
  RAVXOD:
    density: 0.179
  RUTNOK:
    density: 0.241
  SADLEQ:
    density: 1.505
  SAPBIW:
    density: 0.306
  SICZOV:
    density: 0.420
  TOHSAL:
    density: 0.576
  UKUPUL:
    density: 1.434
  VETTIZ:
    density: 0.538
  WIYMOG:
    density: 0.408
  WUNSEE01:
    density: 1.209
  XAFFAN:
    density: 0.365
  XAFXOT:
    density: 1.888
  XAHQAA:
    density: 0.170
  XALTIP:
    density: 0.551
  XUKYEI:
    density: 0.287
  XUWVUG:
    density: 3.194
  YEQRIV:
    density: 0.742

gases:
  - CO2
  - N2
  - O2
